# Generated by Django 4.1.4 on 2022-12-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('RUN', 'run'), ('STOP', 'stop')], default='STOP', max_length=10),
        ),
    ]
